language: br
default_channel: local
bungeecord:
  use: false
  channel: bungeecord
check_for_updates: true
log_to_bukkit: false
log_to_file:
  use: false
  time: 10
block_repeated_tags: true
show_no_one_hears_you: true
block_shortcuts_when_cancelled: true
force_remove_double_spaces_from_bukkit: true
send_fake_message_to_chat: true
maintain_spy_mode: false
text_to_tag: []
format:
  default: '{color}[{nick}] {groupprefix}{prefix}{bprefix2}{bprefix}&f{sender}{bsuffix}{suffix}{groupsuffix}{color}: {msg}'
  bungeecord: '{color}[{nick}] -{server}- {groupprefix}{prefix}{bprefix2}{bprefix}&f{sender}{bsuffix}{suffix}{groupsuffix}{color}: {msg}'
  spy: '&8[SPY] &7{msg}'
private_message_format:
  send: '&6[&ePara {receiver}&6]&f: {msg}'
  receive: '&6[&eDe {sender}&6]&f: {msg}'
  spy: '&8[SPY] &f{ignored} &7[{sender} -> {receiver}] {msg}'
censor:
  use: false
  censored_words:
  - censor_with_stars
  - censor_with_replace;replace_here
